services:
  - docker
env:
  global:
    - IMAGE_NAME="redoracle/nixos_2.2.2"
    - DOCKER_OPTS="--experimental=true"

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - docker build -t "${IMAGE_NAME}:latest" .

after_script:

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
